apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mariadb.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.secrets.mariadb.dbUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.mariadb.dbPassword | b64enc }}
