apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.ports.servicePort }}
      targetPort: {{ .Values.nginx.ports.containerPort }}

