version: '3.8'

services:
  # Service pour la base de données MariaDB
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  # Service pour WordPress
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - wordpress_net
    ports:
      - "8080:80" # WordPress accessible sur le port 8080

  # Service pour Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html  # Utiliser le volume partagé
    ports:
      - "80:80" # Nginx écoute sur le port 80
    networks:
      - wordpress_net

networks:
  wordpress_net:
    driver: bridge

volumes:
  db_data:
  wordpress_data:  # Volume partagé entre WordPress et Nginx
