version: '3.8'

services:
  wordpress:
    build: ./wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
       - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp_network
    ports:
      - "9000:80"  # Mappe le port 9000 de l'hôte vers le port 80 du conteneur

  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "90:80"  # Mappe le port 80 de l'hôte vers le port 80 du conteneur
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

volumes:
  wordpress_data:
  db_data:

networks:
  wp_network:
