apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  name: movie-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie-service
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-service
        app: movie-db
    spec:
      containers:
        - name: movie-service
        - name: movie-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
