# movie-db.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie_db
  template:
    metadata:
      labels:
        app: movie_db
    spec:
      containers:
        - name: movie_db
          image: postgres:12.1-alpine
          env:
            - name: POSTGRES_USER
              value: "movie_db_username"
            - name: POSTGRES_PASSWORD
              value: "movie_db_password"
            - name: POSTGRES_DB
              value: "movie_db_dev"
          volumeMounts:
            - name: postgres-data-movie
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: movie_db
  namespace: default
spec:
  selector:
    app: movie_db
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP
