apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: movie-db
