
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "{{ .Values.env.DATABASE_URI }}"
            - name: CAST_SERVICE_HOST_URL
              value: "{{ .Values.env.CAST_SERVICE_HOST_URL }}"
          volumeMounts:
            - name: cast-db-data
              mountPath: /var/lib/postgresql/data/
      volumes:
      - name: cast-db-data
        persistentVolumeClaim:
          claimName: cast-db-pvc
