apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 8002
    targetPort: {{ .Values.Service.targetPort }}
  selector:
    app: cast-service
---    
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP
