nginx:
  image: nginx:latest
  ports:
    containerPort: 8090
    servicePort: 8090
<<<<<<< HEAD
  volumes:
  - name: nginx-service-volume
    hostPath:
      path: /etc/nginx/conf.d/default.conf
      type: Directory
  volumeMounts:
  - name: nginx-service-volume
    mountPath: ./nginx_config.conf
=======
>>>>>>> 99d8f5707fbb562c3b4d748ea3c827b19f73b2af
  dependencies:
    - cast-service
    - movie-service

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

