nginx:
  image: nginx:latest
  ports:
    containerPort: 8090
    servicePort: 8090
  dependencies:
    - cast-service
    - movie-service

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

