# Utiliser l'image officielle de MariaDB
FROM mariadb:latest

# Ajouter un fichier de configuration personnalisé pour MariaDB si nécessaire (facultatif)
# COPY my_custom.cnf /etc/mysql/conf.d/

# Exposer le port 3306 pour la communication avec la base de données
EXPOSE 3306
