# mariadb/Dockerfile
FROM mariadb:latest
COPY my.cnf /etc/mysql/my.cnf
EXPOSE 3306





# ----------------------- my -------------
# # Utiliser l'image officielle de MariaDB
# FROM mariadb:latest

# # Exposer le port 3306 pour la communication avec la base de données
# EXPOSE 3306
