image: mariadb:latest
rootPassword: example_root_password
user: wordpress_user
password: wordpress_password
database: wordpressdb

persistence:
  enabled: true
  storageClass: "standard"  
  size: 10Gi  # Taille du volume de la base de données
