---
# tasks file for wordpress_role
- name: generate compose file wordpress
  template:
    src: "wordpress-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/wordpress-compose.yaml"
    mode: "0555"
  tags: start

- name: start stack wordpress
  command: "docker compose -f /home/{{ ansible_user }}/wordpress-compose.yaml up -d"
  tags: start

- name: stop stack wordpress
  command: "docker compose -f /home/{{ ansible_user }}/wordpress-compose.yaml down -v"
  tags: delete

- name: delete compose file
  command: "rm -rf /home/{{ ansible_user }}/wordpress-compose.yaml"
  tags: delete