apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image }}"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          value: "{{ .Values.db.database }}"
        - name: WORDPRESS_DB_HOST
          value: "{{ .Values.db.host }}"
        - name: WORDPRESS_DB_USER
          value: "{{ .Values.db.user }}"
        - name: WORDPRESS_DB_PASSWORD
          value: "{{ .Values.db.password }}"
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
          
