apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  containers:
      - name: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.servicePort }}
      targetPort: {{ .Values.nginx.containerPort }}
  type: NodePort
