apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        ports:
        - containerPort: {{ .Values.wordpress.containerPort }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.wordpress.dbHost }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.wordpress.dbUser }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.wordpress.dbPassword }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.wordpress.dbName }}
