apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.image }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.rootPassword }}"
        - name: MYSQL_USER
          value: "{{ .Values.user }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.password }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.database }}"
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
