---
# tasks file for mariadb_role
- name: generate compose file mariadb
  template:
    src: "mariadb-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/mariadb-compose.yaml"
    mode: "0555"
  tags: start

- name: start stack mariadb
  command: "docker compose -f /home/{{ ansible_user }}/mariadb-compose.yaml up -d"
  tags: start

- name: stop stack mariadb
  command: "docker compose -f /home/{{ ansible_user }}/mariadb-compose.yaml down -v"
  tags: delete

- name: delete compose file
  command: "rm -rf /home/{{ ansible_user }}/mariadb-compose.yaml"
  tags: delete