apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  rootPassword: "d2ViLXNlcnZlci1wcm9qZWN0X21hcmlhZGItcm9vdC1wYXNzd29yZA=="
  dbUser: "d2ViLXNlcnZlci1wcm9qZWN0X21hcmlhZGItdXNlcg=="
  dbPassword: "d2ViLXNlcnZlci1wcm9qZWN0X21hcmlhZGItdXNlci1wYXNzd29yZA=="
