apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen 80;

          server_name web-server-project.com;
  
          root /var/www/html;  # Le volume partagé avec WordPress
  
          index index.php index.html index.htm;
  
          # Les règles de réécriture WordPress
          location / {
              try_files $uri $uri/ /index.php?$args;
          }
  
          location ~ \.php$ {
              fastcgi_pass wordpress:9000;  # Le conteneur WordPress (PHP-FPM)
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }  
          location ~ /\.ht {
              deny all;
        }
      }
    }
