apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: web-server-project-app
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.Port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
  type: NodePort
