apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  containers:
      - name: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.Port }}
      containerPort: {{ .Values.nginx.service.containerPort }}
  type: NodePort
