apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
        env:
        - name: WORDPRESS_DB_HOST
          value: "{{ .Values.wordpress.env.WORDPRESS_DB_HOST }}"
        - name: WORDPRESS_DB_NAME
          value: "{{ .Values.wordpress.env.WORDPRESS_DB_NAME }}"
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: dbUser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: dbPassword
          ports:
            - containerPort: 80
