apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  containers:
      - name: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.service.Port }}
      containerPort: {{ .Values.wordpress.service.containerPort }}
  type: NodePort
