apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  containers:
      - name: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.servicePort }}
      targetPort: {{ .Values.wordpress.containerPort }}
  type: NodePort
