apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define('DB_NAME', "{{ .Values.wordpress.env.WORDPRESS_DB_NAME }}");
    define('DB_HOST', "{{ .Values.wordpress.env.WORDPRESS_DB_HOST}}");
    define('DB_USER', "{{ .Values.wordpress.env.WORDPRESS_DB_USER_SECRET }}");
    define('DB_PASSWORD', "{{ .Values.wordpress.env.MYSQL_PASSWORD_SECRET}}");
    define('DB_CHARSET', 'utf8');
    define('DB_COLLATE', '');

    $table_prefix  = 'wp_';

    define('WP_DEBUG', false);

  