apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.service.Port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
  #type: NodePort
